[loggers]
keys=root,app

[handlers]
keys=console,file

[formatters]
keys=generic

[logger_root]
level=INFO
handlers=console,file

[logger_app]
level=DEBUG
handlers=console,file
qualname=app

[handler_console]
class=StreamHandler
level=INFO
formatter=generic

[handler_file]
class=FileHandler
level=DEBUG
formatter=generic
filename=logs/app.log

[formatter_generic]
format=%(asctime)s - %(name)s - %(levelname)s - %(filename)s - %(lineno)d - %(message)s
datefmt=%Y-%m-%d %H:%M:%S